### ISSUE TITLE
Unable to figure out the error with Onion Messenger 

### ISSUE THREAD

**Issue by niteshbalusu11** [lightningdevkit/ldk-garbagecollected#164]
I am trying to use LDK typescript bindings to implement some onion messenger stuff. Can anyone explain me what this error is? I tried debugging for a long time but I cannot figure it out.

Here is the typescript code if you want to look at:
https://github.com/niteshbalusu11/onion-messenger

```
RuntimeError: call_indirect to a null table entry (evaluating 'bindings.OnionMessageHandler_next_onion_message_for_peer(this.ptr, bindings.encodeUint8Array(bindings.check_arr_len(peer_node_id, 33)))')
      at WASM  ([wasm code])
      at WASM  ([wasm code])
      at WASM  ([wasm code])
      at next_onion_message_for_peer (/Users/nitesh/Documents/onion-messenger/node_modules/lightningdevkit/structs/OnionMessageHandler.mjs:124:30)
      at /Users/nitesh/Documents/onion-messenger/run.ts:132:28
      at /Users/nitesh/Documents/onion-messenger/run.ts:118:32
````

**Comment by TheBlueMatt** [comment]
Ah, your issue is the blind casting, see https://github.com/niteshbalusu11/onion-messenger/pull/1
